### ISSUE TITLE
Question: libbpf: failed to find kernel BTF type ID of 'cfs_select_task_rq': -3

### ISSUE THREAD

**Issue by duihuhu** [rgushchin/atc#1]
hi，rgushchin:
  I am interesting in your scheduler path in linux kernel. So I clone the "bpfsched.rfc kernel" in your repository and I finished compiling it. Then I clone "atc" example and make in it's directory, this time I get executable file named atc.
 But when I use ./atc -c ls or ./atc -p with number. I get wrong information as following:
"""
libbpf: sec 'sched/cfs_select_task_rq': found 2 CO-RE relocations
libbpf: prog 'select_task_rq': relo #0: kind <byte_off> (0), spec is [6] struct task_struct.se (0:18 @ offset 128)
libbpf: prog 'select_task_rq': relo #0: matching candidate #0 [130] struct task_struct.se (0:20 @ offset 192)
libbpf: prog 'select_task_rq': relo #0: patched insn #21 (ALU/ALU64) imm 128 -> 192
libbpf: prog 'select_task_rq': relo #1: kind <byte_off> (0), spec is [6] struct task_struct.se (0:18 @ offset 128)
libbpf: prog 'select_task_rq': relo #1: matching candidate #0 [130] struct task_struct.se (0:20 @ offset 192)
libbpf: prog 'select_task_rq': relo #1: patched insn #35 (ALU/ALU64) imm 128 -> 192
libbpf: failed to find kernel BTF type ID of 'cfs_select_task_rq': -3
libbpf: failed to load object 'atc_bpf'
libbpf: failed to load BPF skeleton 'atc_bpf': -3
Failed to load and verify BPF skeleton
""""
   I don't know why does it and how can I tackle it . Can you give me some suggestion? Thanks very much.
Look forward to your favourable reply,
duihuhu

**Comment by rgushchin** [comment]
Hi!
Sorry, I pushed a commit (new hook) that requires a custom kernel. I've reverted it, please, try again.

**Comment by duihuhu** [comment]
> Hi! Sorry, I pushed a commit (new hook) that requires a custom kernel. I've reverted it, please, try again.
hi, rgushchin:
thanks for your reply.
This time I git clone 5.16.0-rc2 version linux in "torvalds/linux" repository. And use "[PATCH rfc 0/6] Scheduler BPF" to patch it. Then , I compile both the linux and "atc". Last , I use ./atc -c ls or ./atc -p with number. I get another wrong information as following:
"""
libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': 0
libbpf: map 'atc_bpf.bss': created successfully, fd=4
libbpf: sec 'sched/cfs_check_preempt_wakeup': found 5 CO-RE relocations
...(this means two many information)
libbpf: prog 'wakeup': relo #2: kind <byte_off> (0), spec is [6] struct task_struct.tgid (0:72 @ offset 2348)
...
libbpf: sec 'sched/cfs_select_task_rq': found 2 CO-RE relocations
libbpf: prog 'select_task_rq': relo #0: kind <byte_off> (0), spec is [6] struct task_struct.se (0:20 @ offset 192)
...
libbpf: failed to find kernel BTF type ID of 'cfs_check_preempt_wakeup': -3
libbpf: failed to load object 'atc_bpf'
libbpf: failed to load BPF skeleton 'atc_bpf': -3
Failed to load and verify BPF skeleton
"""
By the way , my machine linux version is 5.13.0-22-generic. Which step do I wrong? 
Look forward to your favourable reply,
duihuhu

**Comment by rgushchin** [comment]
You need to build and install a custom kernel with the patchset: https://lwn.net/ml/linux-kernel/20210916162451.709260-1-guro@fb.com/ . You also need to build a custom libbpf (with changes from the patchset) and build atc with it.

**Comment by duihuhu** [comment]
> You need to build and install a custom kernel with the patchset: https://lwn.net/ml/linux-kernel/20210916162451.709260-1-guro@fb.com/ . You also need to build a custom libbpf (with changes from the patchset) and build atc with it.

I download the lastest verion linux(5.16.rc3) , build and install this kernel with this patchset. After  rebooting, build a custom libbpf (with changes from the patchset) and build atc with it. But when I run .atc -c ls , I get the same wrong information again:
...
libbpf: failed to find kernel BTF type ID of 'cfs_check_preempt_wakeup': -3
libbpf: prog 'wakeup': failed to prepare load attributes: -3
libbpf: failed to load program 'wakeup'
libbpf: failed to load object 'atc_bpf'
libbpf: failed to load BPF skeleton 'atc_bpf': -3
"""
When I grep 'cfs_check_preempt_wakeup'  in System.map, some information as following:
"""
ffffffff81126b70 T bpf_sched_cfs_check_preempt_wakeup
ffffffff82c5f85c r __BTF_ID__func__bpf_sched_cfs_check_preempt_wakeup__950
"""
Can you tell me which version should I choose?
Look forward to your favourable reply,
duihuhu

**Comment by rgushchin** [comment]
Looks strange. Do other bpf programs (with btf) work? Can you strace it and check where it's failing? Thanks!
